CREATE TABLE user_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_by BIGINT,
   created_date TIMESTAMP WITHOUT TIME ZONE,
   last_modified_by BIGINT,
   last_modified_date TIMESTAMP WITHOUT TIME ZONE,
   currency VARCHAR(255) NOT NULL,
   language VARCHAR(255),
   time_zone VARCHAR(255) NOT NULL,
   CONSTRAINT pk_user_preferences PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_by BIGINT,
   created_date TIMESTAMP WITHOUT TIME ZONE,
   last_modified_by BIGINT,
   last_modified_date TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255),
   email VARCHAR(255),
   password VARCHAR(255),
   user_preferences_id BIGINT,
   verification_code VARCHAR(255),
   status VARCHAR(255),
   last_login TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_USER_PREFERENCES FOREIGN KEY (user_preferences_id) REFERENCES user_preferences (id);